### ISSUE TITLE
Pre-trained model weight Google Drive link is not working

### ISSUE THREAD

**Issue by xiaoran-roosevelt** [liuzhuang13/anytime#2]
Hello,

Thank you for sharing your work and providing the pre-trained model weights. However, I encountered an issue with the Google Drive link for the pre-trained weights. It seems that the link is no longer accessible or has expired.

Could you please provide an updated link or alternative method to access the pre-trained weights?

Thank you for your assistance!

**Comment by OscarXZQ** [comment]
Hi,

Thanks for your interest in our work. The link has been updated.
